# Loads default set of integrations. Do not remove.
default_config:

sensor:
  - platform: roblox
    api_key: !secret roblox_api_key
    hassip: "home"
    accounts: !secret roblox_accounts


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

debugpy:
  start: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
