# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

zha:
  zigpy_config:
    ota:
      inovelli_provider: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

zha_toolkit:

utility_meter:
  daily_propane:
    source: sensor.propane_tank_usage
    cycle: daily
  monthly_propane:
    source: sensor.propane_tank_usage
    cycle: monthly
  yearly_propane:
    source: sensor.propane_tank_usage
    cycle: yearly

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
