name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          scripts:
            - scripts/**
            - .github/**
          config:
            - config/**
            - .github/**

    - name: Set up Python
      if: steps.changes.outputs.scripts == 'true'
      uses: actions/setup-python@v5
      with:
        python-version-file: scripts/.python-version

    - name: Install Poetry
      if: steps.changes.outputs.scripts == 'true'
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Generate requirements.txt
      if: steps.changes.outputs.scripts == 'true'
      run: poetry export --directory=scripts --without-hashes --format=requirements.txt > scripts/requirements.txt

    - name: Copy Scripts to Home Assistant
      if: steps.changes.outputs.scripts == 'true'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: scripts/appdaemon.yaml,scripts/requirements.txt
        target: ${{ secrets.SSH_PATH_SCRIPTS }}
        rm: true
        strip_components: 1

    - name: Copy Scripts to Home Assistant
      if: steps.changes.outputs.scripts == 'true'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: scripts
        target: ${{ secrets.SSH_PATH_SCRIPTS }}/apps
        strip_components: 1